#General mod settings
[general]
	#-
	# Default: 1124
	# Range: > -2147483648
	Misc_simBoxRadiusCutoff = 1124
	#-
	# Default: 1024
	# Range: > -2147483648
	Misc_simBoxRadiusSpawn = 1024
	#If true, lets server side do vanilla weather rules, weather2 will only make storms when server side says 'rain' is on
	overcastMode = false
	#Used if overcastMode is off, 1 = lock weather on, 0 = lock weather off, -1 = dont lock anything, let server do whatever
	# Default: 0
	# Range: > -2147483648
	lockServerWeatherMode = 0
	#How many ticks between cloud particle spawning
	# Default: 2
	# Range: > -2147483648
	Cloud_ParticleSpawnDelay = 2
	#Distance between cloud formations, not particles, this includes invisible cloudless formations used during partial cloud coverage
	# Default: 300
	# Range: > -2147483648
	Cloud_Formation_MinDistBetweenSpawned = 300
	#For a second layer of passive non storm progressing cloudOption
	Cloud_Layer1_Enable = false
	#-
	# Default: 264
	# Range: > -2147483648
	Cloud_Layer0_Height = 264
	#-
	# Default: 414
	# Range: > -2147483648
	Cloud_Layer1_Height = 414
	#Not used at the moment
	# Default: 564
	# Range: > -2147483648
	Cloud_Layer2_Height = 564
	#How much to randomly change cloud coverage % amount, performed every 10 seconds
	# Default: 0.05
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	Cloud_Coverage_Random_Change_Amount = 0.05
	#Minimum percent of cloud coverage, supports negative for extended cloudless sky coverage
	# Default: 0.0
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	Cloud_Coverage_Min_Percent = 4.9E-324
	#Maximum percent of cloud coverage, supports over 100% for extended full cloud sky coverage
	# Default: 100.0
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	Cloud_Coverage_Max_Percent = 100.0
	#-
	# Default: 256.0
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	sirenActivateDistance = 256.0
	#-
	Dimension_List_Weather = "minecraft:overworld, tropicraft:tropicraft"
	#-
	Dimension_List_Clouds = "minecraft:overworld, tropicraft:tropicraft"
	#-
	Dimension_List_Storms = "minecraft:overworld, tropicraft:tropicraft"
	#-
	Dimension_List_WindEffects = "minecraft:overworld, tropicraft:tropicraft"
	#-
	blockBreakingInvokesCancellableEvent = false
	#Server and client side, Locks down the mod to only do wind, leaves, foliage shader if on, etc. No weather systems, turns overcast mode on
	Aesthetic_Only_Mode = false
	#Runs regardless of Aesthetic_Only_Mode, makes snowstorms possible everywhere
	Winter_Wonderland = false
