#General mod settings
[general]
	#Takes the sand out of sandwiches
	Storm_NoSandstorms = false
	#-
	Sandstorm_UseGlobalServerRate = false
	#-
	# Default: 30
	# Range: > -2147483648
	Sandstorm_OddsTo1 = 30
	#Time between sandstorms for either each player or entire server depending on if global rate is on, default: 3 client days
	# Default: 72000
	# Range: > -2147483648
	Sandstorm_TimeBetweenInTicks = 72000
	#Amount of game ticks between sand buildup iterations, keep it high to prevent client side chunk tick spam that destroys FPS
	# Default: 40
	# Range: > -2147483648
	Sandstorm_Sand_Buildup_TickRate = 40
	#Base amount of loops done per iteration, scaled by the sandstorms intensity (value given here is the max possible)
	# Default: 800
	# Range: > -2147483648
	Sandstorm_Sand_Buildup_LoopAmountBase = 200
	#Max height of sand allowed to buildup against something, higher = things get more buried over time
	# Default: 3
	# Range: > -2147483648
	Sandstorm_Sand_Block_Max_Height = 1
	#Allow layered sand blocks to buildup outside deserty biomes where sandstorm is
	Sandstorm_Sand_Buildup_AllowOutsideDesert = true
	#-
	# Default: 0.6
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	Sandstorm_Particle_Dust_effect_rate = 0.6
	#-
	# Default: 0.6
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	Sandstorm_Particle_Debris_effect_rate = 0.1
	#-
	Sandstorm_Siren_PleaseNoDarude = false
