[Timers]
	#Modify the timers for the surface (to reduce or increase them), based on the general timer set (e.g. spawn timer of 300 seconds -> 0.3 turns it into 90 seconds and 1.7 turns it into 510 seconds for the surface)
	# Default: 1.0
	# Range: 0.0 ~ 5.0
	surface_timer_multiplier = 1.0

	[Timers.Spawn]
		#Minimum time between spawns in seconds
		# Default: 300
		# Range: 0 ~ 86400
		can_spawn_min = 600
		#Maximum time between spawns in seconds
		# Default: 600
		# Range: 0 ~ 86400
		can_spawn_max = 1800
		#Chance for a spawn cooldown to occur
		# Default: 0.4
		# Range: 0.0 ~ 1.0
		can_spawn_cooldown_chance = 0.05
		#Spawn cooldown length in seconds
		# Default: 1200
		# Range: 0 ~ 86400
		can_spawn_cooldown = 1800

	[Timers.Noise]
		#Minimum time between noise occurrences in seconds
		# Default: 240
		# Range: 0 ~ 86400
		reset_noise_min = 300
		#Maximum time between noise occurrences in seconds
		# Default: 360
		# Range: 0 ~ 86400
		reset_noise_max = 600

	[Timers.Leave]
		#Time (in seconds) it takes for the Cave Dweller to leave
		# Default: 300
		# Range: 1 ~ 6000
		time_until_leave = 300
		#Time (in seconds) it takes for the Cave Dweller to leave once a chase begins
		# Default: 30
		# Range: 1 ~ 600
		time_until_leave_chase = 60

["Spawn Conditions"]
	#The spawn chance per tick (once the spawn timer is finished)
	# Default: 0.005
	# Range: 0.0 ~ 1.0
	spawn_chance_per_tick = 0.005
	#Depth at which the Cave Dweller can start to spawn
	spawn_height = 0
	#Whether the Cave Dweller can spawn on the surface or not
	allow_surface_spawn = false
	#The maximum sky light level the Cave Dweller can spawn at
	# Default: 8
	# Range: 0 ~ 15
	sky_light_level = 0
	#The maximum block light level the Cave Dweller can spawn at
	# Default: 15
	# Range: 0 ~ 15
	block_light_level = 0
	#The maximum amount of cave dwellers which can exist at the same time
	# Default: 3
	# Range: 0 ~ 100
	maximum_amount = 1
	#How close to players the cave dweller is allowed to spawn (in blocks)
	# Default: 16
	# Range: 0 ~ 64
	spawn_distance = 24
	#If set to true the cave dweller will try to find a spawn position with a possible path to the player
	check_path_to_spawn = true

	["Spawn Conditions".Dimensions]
		#The dimensions where the Cave Dweller can spawn in (Whitelist)
		dimension_whitelist = ["minecraft:overworld"]

	["Spawn Conditions".Biomes]
		#If you don't want to create a datapack to configure the biomes
		override_biome_datapack_config = false
		#Use the surface biome list either as white- or blacklist
		surface_biomes_is_whitelist = false
		#Either white- or blacklist of the surface biomes the Cave Dweller can spawn in (Syntax: modid:biome, e.g. `minecraft:plains`)
		surface_biomes = []

[Behaviour]
	#The distance in blocks at which the Cave Dweller can detect whether a player is looking at it or not
	# Default: 60
	# Range: 0 ~ 128
	spotting_range = 60
	#Whether it can disable shields or not
	can_disable_shields = true
	#Whether the cave dweller can climb or not
	can_climb = true
	#Whether the cave dweller can break down doors or not
	can_break_door = true
	#Time (in seconds) it takes the Cave Dweller to break down a door
	# Default: 3
	# Range: 1 ~ 60
	break_door_time = 6
	#Allow the Cave Dweller to follow vanilla riding logic (e.g. boats)
	allow_riding = false
	#Whether invisible players can be targets or not
	target_invisible = true

[Attributes]
	#Maximum health
	# Default: 450.0
	# Range: 1.0 ~ 100000.0
	maximum_health = 80.0
	#Attack damage
	# Default: 6.0
	# Range: 0.0 ~ 1000.0
	attack_damage = 6.0
	#Attack speed
	# Default: 0.35
	# Range: 0.0 ~ 10.0
	attack_speed = 0.35
	#Movement speed
	# Default: 0.5
	# Range: 0.0 ~ 5.0
	movement_speed = 0.35
	#Depth Strider (movement speed in water) bonus
	# Default: 1.5
	# Range: 0.0 ~ 3.0
	depth_strider_bonus = 1.5

[Misc]
	#Only play the ambient noises to the current (spawn) target (Note: The target can change when a spawn attempt is not successful)
	only_play_noise_to_target = true
