#Settings that effect gameplay, balance, progression, etc.
[gameplay]
	#If set to true, the basic screwdriver will not take damage
	infinite_screwdriver = false
	#If set to false, logic gates will not make sounds
	gate_sounds = true

#Settings that effect performance
[performance]
	#If set to false, logic gates will not emit light. Can help reduce light updates on particularly large and fast-updating redstone circuits.
	gate_lights = true
	#Minimum amount of ticks the timer gates can be set to (min 4). Can be used to enforce lower update rates.
	# Default: 4
	# Range: > 4
	gate_min_timer_ticks = 4
	#Max blocks in a moving frame structure. Limiting this can improve performance on servers where lots of structures are being moved.
	# Default: 1024
	# Range: 1 ~ 4096
	frame_move_limit = 1024
	#Max number of tiles allowed in IC Workbench before auto-compile becomes disallowed (-1 to always allow, 0 to never allow). Recommended to keep this very low on servers.
	# Default: 20
	# Range: > -1
	auto_compile_tile_limit = 20

#World generation settings
[world_gen]
	ruby_ore = true
	sapphire_ore = true
	peridot_ore = true
	tin_ore = true
	silver_ore = true
	electrotine_ore = true
	marble_cave = true
